on: push
name: Deploy Workflow
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: borales/actions-yarn@master
      with:
        args: install
    - name: Build
      uses: borales/actions-yarn@master
      with:
        args: build
    - name: Only Master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Deploy
      uses: maxheld83/ghpages@v0.2.0
      env:
        BUILD_DIR: dist/
        GH_PAT: ${{ secrets.GH_PAT }}
